def gv

pipeline {
    
    agent any
    parameters {
        choice(name: 'VERSION', choices: ['1.1', '1.2'], description: 'version to deploy')
        booleanParam(name: 'executeTests', defaultValue: true, description: 'check if tests have to be run')
    }

    environment {
        NEW_VERSION = '1.3.0'
    }

    stages {

        stage("init") {
            script {
                gv = load "script.groovy"
            }
        }

        stage("build") {

            steps {
                script {
                    gv.buildApp()
                }
            }
        }

        stage("test") {
            when {
                expression {
                    params.executeTests
                }
            }
            steps {
                script {
                    gv.testApp()
                }
            }
        }

        stage("deploy") {

            steps {
                script {
                    gv.testApp()
                }
            }
        }        
    }
}
